### ISSUE TITLE
ping timeout when container connect to another host ip directly 

### ISSUE THREAD

**Issue by piaohai** [zettio/weave#339]
such as follow example : 10.9.2.4 ping 172.17.8.103 time out

[![test](https://raw.githubusercontent.com/piaohai/helloworld/master/1.png?V=1)](https://https://raw.githubusercontent.com/piaohai/helloworld/master/1.png)

**Comment by rade** [comment]
why would you expect that to work? what are you trying to do?

**Comment by piaohai** [comment]
because in some old system,not every infrastructure system run in container network, new system should adapter to old system.

**Comment by rade** [comment]
Did you read about [service import](http://zettio.github.io/weave/features.html#service-import)?

**Comment by bboreham** [comment]
Based on further information supplied via IRC, I think you are seeing two things.  

1: if you run docker with `--iptables=false`, then no container can talk to any off-Docker address.
2: you can set up further routing and NAT rules to get from 10.9.2.4 to core-03 as described at [service import](http://zettio.github.io/weave/features.html#service-import), but this requires that you target the destination using a new IP address within the weave network.  You said you didn't want to give it a different IP address.

So far, this is working as designed.  

There doesn't seem to be any need to involve weave to get from a container on core-02 to core-03, since they are all on the VM network.  You enable this with further `iptables` rules, or let Docker set those up if you change its option to `--iptables=true`

If I have mis-understood any of this I apologise, and please would you supply further information to clarify.
