### ISSUE TITLE
Weave on a RaspberryPi

### ISSUE THREAD

**Issue by guillaumewuip** [zettio/weave#495]
Hi, 

I just want to share with the Weave team some research (like #466) I've done in order to use Weave with Raspberry Pi which is, I think, something that could be cool for IoT.
It was not easy for me and I've write the process to make it work [on medium](https://medium.com/@guillaumewuip/docker-and-weave-on-a-raspberrypi-af208d920a82).

Feel free to close this issue as soon as you read it if you think it's useless. 

Thanks !

**Comment by rade** [comment]
Glad you got it working in the end, and thanks for publishing the instructions. @errordeveloper @fintanr may want to take a closer look and perhaps find ways to simplify the process.

**Comment by errordeveloper** [comment]
@guillaumewuip we certainly do see how Weave may be used as a fundamental building block for connecting devices to the cloud, potentially allowing for cool usecases with microservices distributed all the across etc.

Firstly, I can see that you are using a older revision of weave script, as a workaround #466... There is now a different better way of doing this, you can just grab the weave script from master branch and use with `--local` flag, which will eliminate the need for that tools container image. The only thing to keep in mind is that you will need to have `ip`, `iptables`, `curl` and `ethtools` installed on the the RPi.

Secondly, there are a few approaches that you have gone through, and I understand that it's something you feel like sharing, however it's not making things easy for the reader. My best recommendation would be to leave only a single method, whichever is the simplest one. If you really wish discuss the uncertainties with your audience, you could probably drop those down into comments section, keeping main article short.

**Comment by guillaumewuip** [comment]
Hi @errordeveloper, thanks for you reply.

I've actually just switched project so I won't test the new weave script these days. But I keep this in mind and hope I can try your solution soon.
Thank you also for you feedback about my post. I'll refactor it as soon as I've tested the new weave script.

**Comment by xiamx** [comment]
Hi, @guillaumewuip I'm also interested in this. Do you have any update on this?

**Comment by guillaumewuip** [comment]
Hi @xiamx. Actually I haven't use weave since this try with RaspberryPi. So no, there is nothing new from me.

**Comment by errordeveloper** [comment]
Another user has managed to get it working, let me check with them and I will let you know.

**Comment by cbrown9871** [comment]
Hi @xiamx.  I was able to get weave working on Pi.  Here are the steps I took:

1. Fresh Hypriot/Jessie (that's a 0.5 release), log in
2. apt-get update && apt-get upgrade
3. echo "deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi" >> /etc/apt/sources.list
4. apt-get update && apt-get dist-upgrade
5. apt-get install golang build-essential ethtool iputils-arping libpcap-dev git mercurial bc
6. Run this script:
  export GOPATH=~/gopath
  mkdir $GOPATH
  cd $GOPATH
  go clean -i net
  go install -tags netgo std
  mkdir -p src/github.com/weaveworks
  cd src/github.com/weaveworks
  git clone https://github.com/weaveworks/weave
  cd weave
  git checkout 1.0
  make
7. Note that the build fails with this near the end:
  Status: Downloaded newer image for gliderlabs/alpine:latest
   ---> 5bd56d818842
  Step 1 : MAINTAINER Weaveworks Inc <help@weave.works>
   ---> Running in 03dc69c10b66
   ---> a8da1b2070df
  Removing intermediate container 03dc69c10b66
  Step 2 : RUN apk add --update     curl     ethtool     iptables     iproute2     util-linux     conntrack-tools   && rm -rf /var/cache/apk/*
   ---> Running in 0b102983d17c
  exec format error
  [8] System error: exec format error
  Makefile:78: recipe for target 'weaveexec.tar' failed
  make: *** [weaveexec.tar] Error 1

This is because part of the weave build system currently assumes that it is x86 and depends on an x86 image pulled from the docker registry.

Because of the mentioned build error, "Docker API proxy" will not function.
All weave commands must use '--local' as the first parameter.

8. If desired, inspect resulting container images (there may be additional
    container images, these are the important ones):
  root@rpi-2 ~/gopath/src/github.com/weaveworks/weave # docker images
  REPOSITORY             TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
  weaveworks/weavedns    latest              7b18be319930        About an hour ago   8.426 MB
  weaveworks/weave       latest              3611cdc94cfd        About an hour ago   11.65 MB
9. Install weave executable:
  cp weave /usr/local/bin/
  chmod +x /usr/local/bin/weave

From here I was able to run weave commands, but always remember to add --local.

**Comment by errordeveloper** [comment]
@cbrown9871 thank you very much for the instructions!!

@xiamx @guillaumewuip please let me know if this works for you.

**Comment by guillaumewuip** [comment]
@cbrown9871 thank for your solution, it looks way better than mine :+1:
@errordeveloper sry, I can't test this these days as I'm more than busy

**Comment by xiamx** [comment]
@cbrown9871 Thanks for posting this. I previously arrived to step 7, but thought that weave was unusable without that image. Glad to know that it will work just fine

**Comment by xiamx** [comment]
the alpine linux used by gliderlabs/alpine also has a rpi build according to http://alpinelinux.org/downloads/ It would be interesting to see that image ported to rpi.

**Comment by philipz** [comment]
Hi @guillaumewuip , I have build weave RPi image, philipz/weave, etc...But, weavedns isn't work. I still try to fix it.
https://github.com/philipz/weave

**Comment by errordeveloper** [comment]
Let's ping @progrium regarding Alpine images for the RPi, and see if he has
looked into that.

**Comment by progrium** [comment]
Looping in @andyshinn to see how hard it would be to add support for ARM based Alpine image, perhaps as a tag (`:3.2-arm`, `:latest-arm`?). Not sure if we need to use Raspberry Pi specific build or if we can use the generic ARM build...

**Comment by philipz** [comment]
@errordeveloper , @progrium. The ARM based Alpine image, I use armbuild/alpine.
https://hub.docker.com/r/armbuild/alpine/
The weavedns code in master branch is remove and merge to weaveexec. So, it's work now only on RPi2. 
![weave](https://cloud.githubusercontent.com/assets/664465/9738029/2e982c62-567c-11e5-9bef-24c0f9df3719.png)

**Comment by andyshinn** [comment]
Go ahead and opena n issue at gliderlabs/docker-alpine if there is a need or want for ARM Alpine Docker images. Though, I've been directing people to the armbuild/alpine image for those who have asked. [Scaleway bases their images](https://github.com/scaleway/image-alpine) off the armbuild/alpine image as well

**Comment by philipz** [comment]
Hi all, I have build v1.1.0 for RPi ARMv6 & RPi2 ARMv7 image both. Just like official method. :)
```
sudo curl -L git.io/rpi_weave -o /usr/local/bin/weave
sudo chmod a+x /usr/local/bin/weave
```
